# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish image in Docker Hub

on:
  pull request:
    types: [closed]
    branches:
      - main
      - build
      - g2/task_52/test_workflow

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: docker build -t davidgonmar/uvlhub-egc:v1.0 -f docker/images/Dockerfile.prod .
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

      - name: Push Docker image to Docker Hub
        run: docker push davidgonmar/uvlhub-egc:v1.0

      - name: Tag and push latest
        run: |
          docker tag davidgonmar/uvlhub-egc:v1.0 davidgonmar/uvlhub-egc:latest
          docker push davidgonmar/uvlhub-egc:latest
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
