name: Run Seeders on Render

on:
  workflow_dispatch:

jobs:
  trigger-render-job:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Job
        run: |
          curl --request POST "https://api.render.com/v1/services/srv-cskf2f3tq21c73dnlmgg/jobs" \
               --header "Authorization: Bearer rnd_Dz9r5zVtA5xdO4tFsu47DMykcMmW" \
               --header "Content-Type: application/json" \
               --data-raw '{
                   "startCommand": "rosemary db:seed --reset --yes"
               }'
