name: Run Seeders on Render

on:
  workflow_dispatch:

jobs:
  trigger-render-job:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.RENDER_SSH_KEY }}

      - name: Execute Seed Command on Render via SSH
        env:
          SSH_USER: ${{ secrets.RENDER_SSH_USER }}
          SSH_HOST: ${{ secrets.RENDER_SSH_HOST }}
        run: |
          ssh -t -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << EOF
            bash -l -c "cd /app && rosemary db:seed --reset --yes"
          EOF
